name: build & release
on:
  push:
    branches: [master, devops]
    tags:
      - "*"
env:
  # A-SDK_PATH: /opt/android-sdk-linux
  flutter-version: "3.7.3"
  # TOOL_PATH: /opt/hostedtoolcache/flutter/stable-3.7.3-x64/packages/flutter_tools
  PUB_PATH: .pub-cache
  BUILD_PATH: |
    android/.gradle
    build/*
    !build/app/outputs
    !build/app/outputs/*
jobs:
  build-release:
    runs-on: ubuntu-22.04
    # container:
    # image: cirrusci/flutter:3.7.3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "gradle"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter-version }}
      - name: pub cache
        uses: actions/cache@v3
        with:
          path: ${{ env.PUB_PATH }}
          key: pub-cache
      - name: build cache
        uses: actions/cache@v3
        with:
          path: ${{ env.BUILD_PATH }}
          key: build-cache
      - run: |
          # build release apks

          ## environment setup

          app_ver=$(grep 'version:' pubspec.yaml)
          app_ver=$(echo "${app_ver/'version:'/}" | xargs)
          echo "$app_ver"
          echo "app_ver=$app_ver" >>$GITHUB_ENV

          export PUB_CACHE=$GITHUB_WORKSPACE/.pub-cache
          export PATH="$PATH":"$PUB_CACHE/bin"

          REPO_PATH="$PWD"
          REPO_DIR="$(dirname "$REPO_PATH")"
          REPO_BASE="$(basename "$REPO_PATH")"

          echo "ARTIFACTS_PATH=$REPO_DIR/artifacts" >>$GITHUB_ENV

          cd .. || exit 1  # assuming we have access to the parent dir!

          mkdir artifacts
          cp -r "$REPO_BASE" "$REPO_BASE-split" # &
          # cp -r "$REPO_BASE" "$REPO_BASE-debug" &

          ## build apks

          (cd "$REPO_BASE-split" && {
            flutter pub get
            flutter build apk --release --split-per-abi
            (cd ./build/app/outputs/flutter-apk/ && {
              mv ./app-arm64-v8a-release.apk "$REPO_DIR/artifacts/ble-$app_ver-arm64-v8a.apk"
              mv ./app-armeabi-v7a-release.apk "$REPO_DIR/artifacts/ble-$app_ver-armeabi-v7a.apk"
              mv ./app-x86_64-release.apk "$REPO_DIR/artifacts/ble-$app_ver-x86_64.apk"
            })
          }) # \
          # & # RUNNING THE TWO BUILDS IN PARALLEL, THIS F'S UP THE LOGS!!!
          (cd "$REPO_BASE" && {
            flutter pub get
            flutter build apk --release
            (cd ./build/app/outputs/flutter-apk/ &&
              mv ./app-release.apk $REPO_DIR/artifacts/"ble-$app_ver-universal.apk"
            )
          })
        shell: bash

      - name: Upload build artifacts to releases
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.ARTIFACTS_PATH }}/*.apk
          # token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts to action
        uses: actions/upload-artifact@v3
        with:
          name: v${{ env.app_ver }}
          path: ${{ env.ARTIFACTS_PATH }}/*.apk

