name: build & release
on:
  push:
    branches: [main, devops]
env:
  # app_ver: none
  android_cache: /opt/android-sdk-linux
  flutter_cache: /opt/hostedtoolcache/flutter
  pub_cache: ~/.pub-cache
jobs:
  build-universal:
    runs-on: ubuntu-22.04
    container:
      image: cirrusci/flutter:3.7.3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ${{ env.flutter_cache }}
          key: ${{ runner.os }}-flutter-cache
      - name: cache android sdk????
        uses: actions/cache@v3
        with:
          path: ${{ env.android_cache }}
          key: android-sdk
      - name: pub cache
        uses: actions/cache@v3
        with:
          path: ${{ env.pub_cache }}
          key: pub-cache
      - run: |
          #!/bin/bash
          app_ver=$(grep 'version:' pubspec.yaml)
          app_ver=$(echo "${app_ver/'version:'/}" | xargs)
          echo "$app_ver"
          echo "app_ver=$app_ver" >>$GITHUB_ENV

          flutter pub get
          flutter build apk --release
          (cd ./build/app/outputs/flutter-apk/ &&
            mv ./app-release.apk ./"ble-$app_ver.apk"
          )
      - name: upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-${{ env.app_ver }}
          path: ./build/app/outputs/flutter-apk/

  build-split:
    runs-on: ubuntu-22.04
    container:
      image: cirrusci/flutter:3.7.3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ${{ env.flutter_cache }}
          key: ${{ runner.os }}-flutter-cache
      - name: cache android sdk????
        uses: actions/cache@v3
        with:
          path: ${{ env.android_cache }}
          key: android-sdk
      - name: pub cache
        uses: actions/cache@v3
        with:
          path: ${{ env.pub_cache }}
          key: pub-cache
      - run: |
          #!/bin/bash#
          app_ver=$(grep 'version:' pubspec.yaml)
          app_ver=$(echo "${app_ver/'version:'/}" | xargs)
          echo "$app_ver"
          echo "app_ver=$app_ver" >>$GITHUB_ENV

          flutter pub get
          flutter build apk --release --split-per-abi
          (cd ./build/app/outputs/flutter-apk/ && {
            mv ./app-arm64-v8a-release.apk ./"ble-$app_ver-arm64-v8a.apk"
            mv ./app-armeabi-v7a-release.apk ./"ble-$app_ver-armeabi-v7a.apk"
            mv ./app-x86_64-release.apk ./"ble-$app_ver-x86_64.apk"
          })
      - name: upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: arch-${{ env.app_ver }}
          path: ./build/app/outputs/flutter-apk/

  build-debug:
    runs-on: ubuntu-22.04
    container:
      image: cirrusci/flutter:3.7.3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ${{ env.flutter_cache }}
          key: ${{ runner.os }}-flutter-cache
      - name: cache android sdk????
        uses: actions/cache@v3
        with:
          path: ${{ env.android_cache }}
          key: android-sdk
      - name: pub cache
        uses: actions/cache@v3
        with:
          path: ${{ env.pub_cache }}
          key: pub-cache
      - run: |
          #!/bin/bash#
          app_ver=$(grep 'version:' pubspec.yaml)
          app_ver=$(echo "${app_ver/'version:'/}" | xargs)
          echo "$app_ver"
          echo "app_ver=$app_ver" >>$GITHUB_ENV

          flutter pub get
          flutter build apk --debug
          (cd ./build/app/outputs/flutter-apk/ &&
            mv ./app-debug.apk ./"ble-$app_ver-debug.apk"
          )
      - name: upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debug-${{ env.app_ver }}
          path: ./build/app/outputs/flutter-apk/

  release:
    runs-on: ubuntu-22.04
    needs:
      - build-debug
      - build-universal
      - build-split
    steps:
      - uses: actions/checkout@v3
      - run: |
          #!/bin/bash
          app_ver=$(grep 'version:' pubspec.yaml)
          app_ver=$(echo "${app_ver/'version:'/}" | xargs)
          echo "$app_ver"
          echo "app_ver=$app_ver" >>$GITHUB_ENV
          mkdir ./release
      - name: Download all workflow artifacts
        uses: actions/download-artifact@v3
        with:
          path: release
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/*/*"
          tag: ${{ env.app_ver }}
          # token: ${{ secrets.GITHUB_TOKEN }}
